### ISSUE TITLE
Cryptocurrency demo should fail fast if no twitter/reddit credentials supplied

### ISSUE THREAD

**Issue by dbrimley** [hazelcast/jet-demos#14]
User needs to provide their own twitter and reddit login details.

If left with the defaults in the properties files the following confusing error is produced...

```
Exception in thread "hz._hzInstance_1_dev.cached.thread-2" java.lang.IllegalArgumentException: Output ordinals for vertex aggregateTrend15Min are not ordered. Actual: [1] Expected: [0]
	at com.hazelcast.jet.core.DAG.validateOutboundEdgeOrdinals(DAG.java:279)
	at com.hazelcast.jet.core.DAG.validate(DAG.java:244)
	at com.hazelcast.jet.core.DAG.iterator(DAG.java:215)
	at com.hazelcast.jet.impl.MasterContext.tryStartJob(MasterContext.java:171)
	at com.hazelcast.jet.impl.JobCoordinationService.tryStartJob(JobCoordinationService.java:267)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitOrJoinJob$1(JobCoordinationService.java:191)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```

**Comment by eminn** [comment]
Fixed via https://github.com/hazelcast/jet-demos/commit/07dcc01a5b87a0cf0b977c9baa0d1ffad5f17022
