### ISSUE TITLE
flight-telemetry : ClassCastException

### ISSUE THREAD

**Issue by dbrimley** [hazelcast/jet-demos#16]
I followed the set-up instructions in the Readme and running the application I get the following....

```
49:25,663 [172.19.0.1]:5702 [jet] [0.6-SNAPSHOT] Exception in ProcessorTasklet{vertex=addVerticalDirection, processor=com.hazelcast.jet.impl.processor.TransformP@78e38ade}
java.lang.ClassCastException: com.hazelcast.jet.datamodel.Tuple2 cannot be cast to java.util.List
	at com.hazelcast.jet.demo.Demo.assignDirection(Demo.java:286)
	at com.hazelcast.jet.core.processor.Processors.lambda$null$a61c02b4$1(Processors.java:673)
	at com.hazelcast.jet.core.AbstractProcessor$FlatMapper.tryProcess(AbstractProcessor.java:585)
	at com.hazelcast.jet.impl.processor.TransformP.tryProcess(TransformP.java:44)
	at com.hazelcast.jet.core.AbstractProcessor.tryProcess0(AbstractProcessor.java:205)
	at com.hazelcast.jet.core.AbstractProcessor.process0(AbstractProcessor.java:613)
	at com.hazelcast.jet.core.AbstractProcessor.process(AbstractProcessor.java:127)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:183)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:154)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:141)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:134)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:230)
	at java.lang.Thread.run(Thread.java:748)
49:25,668 [172.19.0.1]:5702 [jet] [0.6-SNAPSHOT] Exception in ProcessorTasklet{vertex=addVerticalDirection, processor=com.hazelcast.jet.impl.processor.TransformP@627cd94b}
java.lang.ClassCastException: com.hazelcast.jet.datamodel.Tuple2 cannot be cast to java.util.List
	at com.hazelcast.jet.demo.Demo.assignDirection(Demo.java:286)
	at com.hazelcast.jet.core.processor.Processors.lambda$null$a61c02b4$1(Processors.java:673)
	at com.hazelcast.jet.core.AbstractProcessor$FlatMapper.tryProcess(AbstractProcessor.java:585)
	at com.hazelcast.jet.impl.processor.TransformP.tryProcess(TransformP.java:44)
	at com.hazelcast.jet.core.AbstractProcessor.tryProcess0(AbstractProcessor.java:205)
	at com.hazelcast.jet.core.AbstractProcessor.process0(AbstractProcessor.java:613)
	at com.hazelcast.jet.core.AbstractProcessor.process(AbstractProcessor.java:127)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:183)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:154)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:141)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:134)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:230)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by eminn** [comment]
Fixed via https://github.com/hazelcast/jet-demos/commit/302792623315a2eb628ed3cbbbbfe259c444a2c9
